import bcrypt from 'bcryptjs'
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'pedro',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Camisetas',
      category: 'a',
      slug: 'camisetas',
      image: '/images/blusa_branca_masculina.jpg',
      price: 10,
      brand: 'ai',
      rating: 5,
      numReviews: 10,
      countInStock: 10,
      description: 'Um item legalzao',
    },
    {
      name: 'b',
      slug: 'camisetas-legais',
      category: 'b',
      image: '/images/',
      price: 10,
      brand: 'ai',
      rating: 5,
      numReviews: 10,
      countInStock: 5,
      description: 'Um item legalzao',
    },
    {
      name: 'c',
      slug: 'camisetas-legais1',
      category: 'b',
      image: '/images/',
      price: 10,
      brand: 'oi',
      rating: 5,
      numReviews: 10,
      countInStock: 2,
      description: 'Um item legalzao',
    },
    {
      name: 'd',
      slug: 'camisetas-legais2',
      category: 'a',
      image: '/images/',
      price: 10,
      brand: 'oi',
      rating: 5,
      numReviews: 10,
      countInStock: 2,
      description: 'Um item legalzao',
    },
  ],
};
export default data;
