const data = {
  products: [
    {
      name: 'a',
      category: 'a',
      image: '/images/',
      price: 10,
      brand: 'ai',
      rating: 5,
      numReviews: 10,
      countInStock: 2,
      description: 'Um item legalzao',
    },
    {
      name: 'b',
      category: 'b',
      image: '/images/',
      price: 10,
      brand: 'ai',
      rating: 5,
      numReviews: 10,
      countInStock: 2,
      description: 'Um item legalzao',
    },
    {
      name: 'c',
      category: 'b',
      image: '/images/',
      price: 10,
      brand: 'oi',
      rating: 5,
      numReviews: 10,
      countInStock: 2,
      description: 'Um item legalzao',
    },
    {
      name: 'd',
      category: 'a',
      image: '/images/',
      price: 10,
      brand: 'oi',
      rating: 5,
      numReviews: 10,
      countInStock: 2,
      description: 'Um item legalzao',
    },
  ],
};
export default data;
